receivers:
  webhookevent:
    endpoint: "localhost:8088"
    path: "/webhook"
  githubactionslog:
    github_auth:
      token: ${env:GITHUB_TOKEN}

processors:
  batch:

extensions:
  zpages:
    endpoint: "localhost:55679"

exporters:
  elasticsearch/log:
    endpoints:
      - http://localhost:9200
    logs_index: logs-github-actions-1
    sending_queue:
      enabled: true
      num_consumers: 20
      queue_size: 1000
  debug:
    verbosity: basic

service:
  extensions: [zpages]
  pipelines:
    logs:
      receivers: [githubactionslog]
      exporters:
#        - elasticsearch/log
        - debug
  telemetry:
    logs:
      level: debug
