apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otelcol-github-actions.fullname" . }}-otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
  {{- include "otelcol-github-actions.labels" . | nindent 4 }}
  annotations:
    configmap.reloader.stakater.com/reload: {{ include "otelcol-github-actions.fullname" . }}-otelcol-config
    secret.reloader.stakater.com/reload: {{ include "otelcol-github-actions.fullname" . }}-github-app-credentials,{{ include "otelcol-github-actions.fullname" . }}-observability-ci-cluster-credentials
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
    {{- include "otelcol-github-actions.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
      {{- include "otelcol-github-actions.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - command:
            - /otelcol-custom
            - --config=/conf/config.yml
          env: {{- toYaml .Values.extraEnv | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "otelcol-github-actions.fullname" . }}-observability-ci-cluster-credentials
            - secretRef:
                name: {{ include "otelcol-github-actions.fullname" . }}-github-app-credentials
          image: {{ .Values.image.repository }}:{{ .Values.image.tag
          | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: {{ include "otelcol-github-actions.receiver.port" . }}
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: otel-collector
          ports:
            - containerPort: {{ include "otelcol-github-actions.receiver.port" . }}
            - containerPort: 1777 # pprof
            - containerPort: 55679 # zpages
            - containerPort: 8888 # metrics
            - containerPort: 19418 # githubactionsreceiver
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: {{ include "otelcol-github-actions.receiver.port" . }}
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources: {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /conf
              name: otel-collector-config-vol
      serviceAccountName: {{ include "otelcol-github-actions.fullname" . }}-otel-collector
      volumes:
        - configMap:
            name: {{ include "otelcol-github-actions.fullname" . }}-otelcol-config
          name: otel-collector-config-vol
