---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "otelcol-github-actions.fullname" . }}-observability-ci-cluster-credentials
  labels:
  {{- include "otelcol-github-actions.labels" . | nindent 4 }}
spec:
  data:
    - remoteRef:
        key: oblt-clusters_observability-ci_elasticsearch_username
      secretKey: elasticsearch_username
    - remoteRef:
        key: oblt-clusters_observability-ci_elasticsearch_password
      secretKey: elasticsearch_password
    - remoteRef:
        key: oblt-clusters_observability-ci_elasticsearch_url
      secretKey: elasticsearch_url
    - remoteRef:
        key: oblt-clusters_observability-ci_apm_url
      secretKey: apm_url
    - remoteRef:
        key: oblt-clusters_observability-ci_apm_token
      secretKey: apm_token
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ include "otelcol-github-actions.fullname" . }}-gcp-store-elastic-observability
  target:
    creationPolicy: Owner
    name: {{ include "otelcol-github-actions.fullname" . }}-observability-ci-cluster-credentials
    template:
      data:
        ELASTICSEARCH_USERNAME: "{{ `{{ .elasticsearch_username }}` }}"
        ELASTICSEARCH_PASSWORD: "{{ `{{ .elasticsearch_password }}` }}"
        ELASTICSEARCH_URL: "{{ `{{ .elasticsearch_url }}` }}"
        APM_URL: "{{ `{{ .apm_url }}` }}"
        APM_TOKEN: "{{ `{{ .apm_token }}` }}"
      engineVersion: v2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "otelcol-github-actions.fullname" . }}-github-app-credentials
  labels:
  {{- include "otelcol-github-actions.labels" . | nindent 4 }}
spec:
  dataFrom:
    - extract:
        key: observability-ci_github-app
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: {{ include "otelcol-github-actions.fullname" . }}-gcp-store-elastic-observability-ci
  target:
    creationPolicy: Owner
    name: {{ include "otelcol-github-actions.fullname" . }}-github-app-credentials
    template:
      data:
        GITHUB_APP_ID: "{{ `{{ .app_id }}` }}"
        GITHUB_APP_PRIVATE_KEY: "{{ `{{ .key | b64enc }}` }}"
        GITHUB_INSTALLATION_ID: "{{ `{{ .installation_id }}` }}"
        WEBHOOK_SECRET: "{{ `{{ .webhook_secret }}` }}"
      engineVersion: v2
