---
# SecretStore for elastic-observability GCP project
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "otelcol-github-actions.fullname" . }}-gcp-store-elastic-observability
  labels:
  {{- include "otelcol-github-actions.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: "(redacted)"
---
# SecretStore for elastic-observability-ci GCP project
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "otelcol-github-actions.fullname" . }}-gcp-store-elastic-observability-ci
  labels:
  {{- include "otelcol-github-actions.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: "(redacted)"
