apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "otelcol-github-actions.fullname" . }}-otel-collector
  labels:
  {{- include "otelcol-github-actions.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
