dist:
  name: otelcol-custom
  output_path: ./bin
  otel_version: 0.102.0

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.102.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.102.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.102.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.102.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/backstageprocessor v0.102.0
    path: ./ga-backstageprocessor

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.102.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.102.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/githubactionslogreceiver v0.102.0
    path: ./githubactionslogsreceiver
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/githubactionsreceiver v0.102.0
    path: ./githubactionstracesreceiver
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/githubactionsannotationsreceiver v0.102.0
    path: ./githubactionsannotationsreceiver

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.102.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.102.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.102.0
