dist:
  name: otelcol-custom
  output_path: ./bin

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.96.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter v0.96.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.96.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.96.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.96.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/githubactionslogreceiver v0.96.0
    import: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/githubactionslogreceiver
    path: ./githubactionslogreceiver

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.96.0
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.96.0
