name: Build and Publish

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      collector_ref:
        description: 'The ref of the opentelemetry-collector-contrib repository to use.'
        required: true
        default: 'feature/githubactionslogsreceiver'


env:
  DOCKER_IMAGE_NAME: reakaleek/otelcol-githubactions

concurrency:
  group: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' && github.workflow || github.run_id }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image name
        id: image
        run: |
          otel_version=$(yq -r '.dist.otel_version' docker/builder-config.yml)
          name="${DOCKER_IMAGE_NAME}:${otel_version}-githubactionsreceiver"
          echo "name=${name}" >> "${GITHUB_OUTPUT}"

      - if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: reakaleek
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: docker
          tags: |
            ${{ steps.image.outputs.name }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest
          push: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
          no-cache: true
