name: Build and Publish

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      collector_ref:
        description: 'The ref of the opentelemetry-collector-contrib repository to use.'
        required: true
        default: 'feature/githubactionslogsreceiver'


env:
  OTEL_VERSION: 0.98.0
  DOCKER_IMAGE_NAME: reakaleek/otelcol-custom

concurrency:
  group: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' && github.workflow || github.run_id }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: opentelemetry-collector-githubactionslogreceiver-dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: checkout krzko/opentelemetry-collector-contrib@edc0f22d7deb6563a236daef5558f1e971a81c5d
        uses: actions/checkout@v4
        with:
          repository: unelastisch/opentelemetry-collector-contrib
          ref: 7a56336ef9162f1a7d88f0a5c1847320be5b47cd
          path: krzko-opentelemetry-collector-contrib
          sparse-checkout: receiver/githubactionsreceiver

      - name: checkout reakaleek/opentelemetry-collector-contrib@feature/githubactionslogsreceiver
        uses: actions/checkout@v4
        with:
          repository: reakaleek/opentelemetry-collector-contrib
          ref: ${{ inputs.collector_ref || 'feature/githubactionslogsreceiver' }}
          path: opentelemetry-collector-contrib
          sparse-checkout: receiver/githubactionslogreceiver

      - name: checkout v1v/opentelemetry-github-actions-annotations-receiver@feature/send-annotations
        uses: actions/checkout@v4
        with:
          repository: v1v/opentelemetry-github-actions-annotations-receiver
          ref: 'feature/send-annotations'
          path: v1v-opentelemetry-collector-contrib

      - name: Generate image name
        id: image
        working-directory: opentelemetry-collector-contrib
        run: |
          commit=$(git rev-parse --short HEAD)
          name="${DOCKER_IMAGE_NAME}:${OTEL_VERSION}-githubactionslogreceiver-${commit}"
          echo "name=${name}" >> "${GITHUB_OUTPUT}"

      - name: Generate githubactionslogreceiver
        working-directory: opentelemetry-collector-githubactionslogreceiver-dev/docker
        run: make githubactionslogreceiver

      - name: Copy githubactionsreceiver
        working-directory: opentelemetry-collector-githubactionslogreceiver-dev/docker
        run: |
          cp -r ../../krzko-opentelemetry-collector-contrib/receiver/githubactionsreceiver ./githubactionsreceiver


      - name: Copy githubactionsannotationsreceiver
        working-directory: opentelemetry-collector-githubactionslogreceiver-dev/docker
        run: |
          cp -r v1v-opentelemetry-collector-contrib ./githubactionsannotationsreceiver

      - if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: reakaleek
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: opentelemetry-collector-githubactionslogreceiver-dev/docker
          tags: |
            ${{ steps.image.outputs.name }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest
          push: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
          build-args: |
            OTEL_VERSION=${{ env.OTEL_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          no-cache: true

